# Generated by Django 4.1.7 on 2023-03-21 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fno', models.IntegerField(default=0)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
