# Generated by Django 4.1.7 on 2023-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=10)),
                ('attendence', models.FloatField()),
                ('subjects', models.JSONField()),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
    ]
