# Generated by Django 4.1.7 on 2023-03-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_data',
        ),
    ]
